image: ocaml/opam2:4.09

build:
  stage: build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - _opam
  script:
  - sudo apt install -y m4 libgmp-dev pkg-config
  - git submodule init
  - git submodule update
  - opam remote add official https://opam.ocaml.org/
  - opam update
  - '[ -d _opam ] || opam switch create . ocaml-base-compiler.4.09.1'
  - opam install -y ./scaml.opam
