lib: [
  "_build/install/default/lib/ppx_type_of/META"
  "_build/install/default/lib/ppx_type_of/dune-package"
  "_build/install/default/lib/ppx_type_of/mod.ml"
  "_build/install/default/lib/ppx_type_of/opam"
  "_build/install/default/lib/ppx_type_of/ppx.ml"
  "_build/install/default/lib/ppx_type_of/ppx_type_of.a"
  "_build/install/default/lib/ppx_type_of/ppx_type_of.cma"
  "_build/install/default/lib/ppx_type_of/ppx_type_of.cmi"
  "_build/install/default/lib/ppx_type_of/ppx_type_of.cmt"
  "_build/install/default/lib/ppx_type_of/ppx_type_of.cmx"
  "_build/install/default/lib/ppx_type_of/ppx_type_of.cmxa"
  "_build/install/default/lib/ppx_type_of/ppx_type_of.cmxs"
  "_build/install/default/lib/ppx_type_of/ppx_type_of.ml"
  "_build/install/default/lib/ppx_type_of/ppx_type_of__Mod.cmi"
  "_build/install/default/lib/ppx_type_of/ppx_type_of__Mod.cmt"
  "_build/install/default/lib/ppx_type_of/ppx_type_of__Mod.cmx"
  "_build/install/default/lib/ppx_type_of/ppx_type_of__Ppx.cmi"
  "_build/install/default/lib/ppx_type_of/ppx_type_of__Ppx.cmt"
  "_build/install/default/lib/ppx_type_of/ppx_type_of__Ppx.cmx"
]
libexec: [
  "_build/install/default/lib/ppx_type_of/ppx.exe"
]
doc: [
  "_build/install/default/doc/ppx_type_of/README.md"
]
